### ISSUE TITLE
App Configuration Reference not resolved in FunctionApp

### ISSUE THREAD

**Issue by jplavka** [Azure/AppConfiguration#828]
Hi, 
We are using App Configuration References in Function Apps (Isolated/.NET7) in different regions, but it somehow stopped to work for North Europe region. We changed App Service Plan to EP2 and it worked for a while but then once again we have problem to resolve references, Key vault reference works fine and resolves everything correctly. In the message we just see status 'OtherReasons'. Any idea what could go wrong or how to debug the problem? 

![AppConfigReference](https://github.com/Azure/AppConfiguration/assets/13344548/410c8b20-b18b-47ac-bc66-e31db36ab0e5)

![AppConfigReference2](https://github.com/Azure/AppConfiguration/assets/13344548/3aaaa78a-5d4b-4d17-b78c-058e23e651b9)

**Comment by avanigupta** [comment]
Hi @jplavka, we found that there was a regression, and it was fixed last week. You shouldn't be seeing these errors anymore. Please let us know if you continue to see these errors in any regions.

**Comment by jplavka** [comment]
Thank you @avanigupta, it works now for EP2, but we also have couple of Function Apps running on Y1 and the problem seems to be not solved there. Should we move all function apps to higher plan in order to avoid this behavior there?

**Comment by avanigupta** [comment]
@jplavka what is the name of your Function App on Y1 plan that's still not able to resolve references?

**Comment by jplavka** [comment]
One of them is "de-prod-neu-targetresolver/staging". Ended up in deployment slot and we are currently not able to swap it.

![image](https://github.com/Azure/AppConfiguration/assets/13344548/f5bceb7a-8317-4248-a8cf-a71913653a37)

**Comment by jplavka** [comment]
Hi @avanigupta,
I have just deployed in East Us 2 region due to failover testing the issue is still there.
Can you check as well this region? Is it region dependent issue at all?

Function name; DE-DR-DTConfiguration/staging
Plan: P1V3

![image](https://github.com/Azure/AppConfiguration/assets/13344548/acdb7588-5269-4f14-91f5-527797e372ce)

**Comment by karshinlin** [comment]
Hi @jplavka - the app is running into a different issue. This one is related to setup. I see that you added your references to the web app first, then enabled MSI, and then presumably added the right RBAC permissions for the MSI in App Config portal.

Since we continuously try to resolve the App Config references to start the web app, we retrieved a token _before_ the RBAC permissions were assigned. This token is cached for up to 24 hours by our platform as well as various AAD dependencies upstream. The error we get when resolving the App Config reference is a 403, likely because the cached token does not have the right claims. This issue should resolve itself if you wait 24 hours and restart the site, or perform these steps:
1. Remove the references (you can always prefix the value @Microsoft.AppConfig with "NotAReference" to avoid having to delete the app settings
2. Disable and re-enable identity
3. Add the RBAC permissions to allow the identity to connect to App Config
4. Add the references back to the app (or remove the prefix you added in step1).

Sorry for the inconvenience with this. The token caching is a limitation of the platform today and we have plans to improve the user experience here.

**Comment by zhenlan** [comment]
Closing as this is a platform limitation and the improvement is tracked separately.
